#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include <pybind11/operators.h>

#include <AppDefs.h>
#include <BeBuild.h>
#include <Cursor.h>

namespace py = pybind11;


PYBIND11_MODULE(AppDefs,m)
{
m.attr("B_ABOUT_REQUESTED") = B_ABOUT_REQUESTED;
m.attr("B_WINDOW_ACTIVATED") = B_WINDOW_ACTIVATED;
m.attr("B_APP_ACTIVATED") = B_APP_ACTIVATED;
m.attr("B_ARGV_RECEIVED") = B_ARGV_RECEIVED;
m.attr("B_QUIT_REQUESTED") = B_QUIT_REQUESTED;
m.attr("B_CLOSE_REQUESTED") = B_CLOSE_REQUESTED;
m.attr("B_CANCEL") = B_CANCEL;
m.attr("B_INVALIDATE") = B_INVALIDATE;
m.attr("B_KEY_DOWN") = B_KEY_DOWN;
m.attr("B_KEY_UP") = B_KEY_UP;
m.attr("B_UNMAPPED_KEY_DOWN") = B_UNMAPPED_KEY_DOWN;
m.attr("B_UNMAPPED_KEY_UP") = B_UNMAPPED_KEY_UP;
m.attr("B_KEY_MAP_LOADED") = B_KEY_MAP_LOADED;
m.attr("B_LAYOUT_WINDOW") = B_LAYOUT_WINDOW;
m.attr("B_MODIFIERS_CHANGED") = B_MODIFIERS_CHANGED;
m.attr("B_MINIMIZE") = B_MINIMIZE;
m.attr("B_MOUSE_DOWN") = B_MOUSE_DOWN;
m.attr("B_MOUSE_MOVED") = B_MOUSE_MOVED;
m.attr("B_MOUSE_ENTER_EXIT") = B_MOUSE_ENTER_EXIT;
m.attr("B_MOUSE_IDLE") = B_MOUSE_IDLE;
m.attr("B_MOUSE_UP") = B_MOUSE_UP;
m.attr("B_MOUSE_WHEEL_CHANGED") = B_MOUSE_WHEEL_CHANGED;
m.attr("B_OPEN_IN_WORKSPACE") = B_OPEN_IN_WORKSPACE;
m.attr("B_PACKAGE_UPDATE") = B_PACKAGE_UPDATE;
m.attr("B_PRINTER_CHANGED") = B_PRINTER_CHANGED;
m.attr("B_PULSE") = B_PULSE;
m.attr("B_READY_TO_RUN") = B_READY_TO_RUN;
m.attr("B_REFS_RECEIVED") = B_REFS_RECEIVED;
m.attr("B_RELEASE_OVERLAY_LOCK") = B_RELEASE_OVERLAY_LOCK;
m.attr("B_ACQUIRE_OVERLAY_LOCK") = B_ACQUIRE_OVERLAY_LOCK;
m.attr("B_SCREEN_CHANGED") = B_SCREEN_CHANGED;
m.attr("B_VALUE_CHANGED") = B_VALUE_CHANGED;
m.attr("B_TRANSLATOR_ADDED") = B_TRANSLATOR_ADDED;
m.attr("B_TRANSLATOR_REMOVED") = B_TRANSLATOR_REMOVED;
m.attr("B_DELETE_TRANSLATOR") = B_DELETE_TRANSLATOR;
m.attr("B_VIEW_MOVED") = B_VIEW_MOVED;
m.attr("B_VIEW_RESIZED") = B_VIEW_RESIZED;
m.attr("B_WINDOW_MOVED") = B_WINDOW_MOVED;
m.attr("B_WINDOW_RESIZED") = B_WINDOW_RESIZED;
m.attr("B_WORKSPACES_CHANGED") = B_WORKSPACES_CHANGED;
m.attr("B_WORKSPACE_ACTIVATED") = B_WORKSPACE_ACTIVATED;
m.attr("B_ZOOM") = B_ZOOM;
m.attr("B_COLORS_UPDATED") = B_COLORS_UPDATED;
m.attr("B_FONTS_UPDATED") = B_FONTS_UPDATED;
m.attr("B_TRACKER_ADDON_MESSAGE") = B_TRACKER_ADDON_MESSAGE;
m.attr("_APP_MENU_") = _APP_MENU_;
m.attr("_BROWSER_MENUS_") = _BROWSER_MENUS_;
m.attr("_MENU_EVENT_") = _MENU_EVENT_;
m.attr("_PING_") = _PING_;
m.attr("_QUIT_") = _QUIT_;
m.attr("_VOLUME_MOUNTED_") = _VOLUME_MOUNTED_;
m.attr("_VOLUME_UNMOUNTED_") = _VOLUME_UNMOUNTED_;
m.attr("_MESSAGE_DROPPED_") = _MESSAGE_DROPPED_;
m.attr("_DISPOSE_DRAG_") = _DISPOSE_DRAG_;
m.attr("_MENUS_DONE_") = _MENUS_DONE_;
m.attr("_SHOW_DRAG_HANDLES_") = _SHOW_DRAG_HANDLES_;
m.attr("_EVENTS_PENDING_") = _EVENTS_PENDING_;
m.attr("_UPDATE_") = _UPDATE_;
m.attr("_UPDATE_IF_NEEDED_") = _UPDATE_IF_NEEDED_;
m.attr("_PRINTER_INFO_") = _PRINTER_INFO_;
m.attr("_SETUP_PRINTER_") = _SETUP_PRINTER_;
m.attr("_SELECT_PRINTER_") = _SELECT_PRINTER_;

m.attr("B_SET_PROPERTY") = B_SET_PROPERTY;
m.attr("B_GET_PROPERTY") = B_GET_PROPERTY;
m.attr("B_CREATE_PROPERTY") = B_CREATE_PROPERTY;
m.attr("B_DELETE_PROPERTY") = B_DELETE_PROPERTY;
m.attr("B_COUNT_PROPERTIES") = B_COUNT_PROPERTIES;
m.attr("B_EXECUTE_PROPERTY") = B_EXECUTE_PROPERTY;
m.attr("B_GET_SUPPORTED_SUITES") = B_GET_SUPPORTED_SUITES;
m.attr("B_UNDO") = B_UNDO;
m.attr("B_REDO") = B_REDO;
m.attr("B_CUT") = B_CUT;
m.attr("B_COPY") = B_COPY;
m.attr("B_PASTE") = B_PASTE;
m.attr("B_SELECT_ALL") = B_SELECT_ALL;
m.attr("B_SAVE_REQUESTED") = B_SAVE_REQUESTED;
m.attr("B_MESSAGE_NOT_UNDERSTOOD") = B_MESSAGE_NOT_UNDERSTOOD;
m.attr("B_NO_REPLY") = B_NO_REPLY;
m.attr("B_REPLY") = B_REPLY;
m.attr("B_SIMPLE_DATA") = B_SIMPLE_DATA;
m.attr("B_MIME_DATA") = B_MIME_DATA;
m.attr("B_ARCHIVED_OBJECT") = B_ARCHIVED_OBJECT;
m.attr("B_UPDATE_STATUS_BAR") = B_UPDATE_STATUS_BAR;
m.attr("B_RESET_STATUS_BAR") = B_RESET_STATUS_BAR;
m.attr("B_NODE_MONITOR") = B_NODE_MONITOR;
m.attr("B_QUERY_UPDATE") = B_QUERY_UPDATE;
m.attr("B_ENDORSABLE") = B_ENDORSABLE;
m.attr("B_COPY_TARGET") = B_COPY_TARGET;
m.attr("B_MOVE_TARGET") = B_MOVE_TARGET;
m.attr("B_TRASH_TARGET") = B_TRASH_TARGET;
m.attr("B_LINK_TARGET") = B_LINK_TARGET;
m.attr("B_INPUT_DEVICES_CHANGED") = B_INPUT_DEVICES_CHANGED;
m.attr("B_INPUT_METHOD_EVENT") = B_INPUT_METHOD_EVENT;
m.attr("B_WINDOW_MOVE_TO") = B_WINDOW_MOVE_TO;
m.attr("B_WINDOW_MOVE_BY") = B_WINDOW_MOVE_BY;
m.attr("B_SILENT_RELAUNCH") = B_SILENT_RELAUNCH;
m.attr("B_OBSERVER_NOTICE_CHANGE") = B_OBSERVER_NOTICE_CHANGE;
m.attr("B_CONTROL_INVOKED") = B_CONTROL_INVOKED;
m.attr("B_CONTROL_MODIFIED") = B_CONTROL_MODIFIED;

m.attr("B_HAND_CURSOR") = B_HAND_CURSOR;

m.attr("B_I_BEAM_CURSOR") = B_I_BEAM_CURSOR;

m.attr("B_CURSOR_SYSTEM_DEFAULT") = B_CURSOR_SYSTEM_DEFAULT;

m.attr("B_CURSOR_I_BEAM") = B_CURSOR_I_BEAM;


}
