#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include <pybind11/operators.h>

#include <AppDefs.h>
#include <BeBuild.h>

namespace py = pybind11;


PYBIND11_MODULE(AppDefs,m)
{
py::enum_<SysMsg>(m, "SysMsg", "")
.value("B_ABOUT_REQUESTED", B_ABOUT_REQUESTED, "")
.value("B_WINDOW_ACTIVATED", SysMsg::B_WINDOW_ACTIVATED, "")
.value("B_APP_ACTIVATED", SysMsg::B_APP_ACTIVATED, "")
.value("B_ARGV_RECEIVED", SysMsg::B_ARGV_RECEIVED, "")
.value("B_QUIT_REQUESTED", SysMsg::B_QUIT_REQUESTED, "")
.value("B_CLOSE_REQUESTED", SysMsg::B_CLOSE_REQUESTED, "")
.value("B_CANCEL", SysMsg::B_CANCEL, "")
.value("B_INVALIDATE", SysMsg::B_INVALIDATE, "")
.value("B_KEY_DOWN", SysMsg::B_KEY_DOWN, "")
.value("B_KEY_UP", SysMsg::B_KEY_UP, "")
.value("B_UNMAPPED_KEY_DOWN", SysMsg::B_UNMAPPED_KEY_DOWN, "")
.value("B_UNMAPPED_KEY_UP", SysMsg::B_UNMAPPED_KEY_UP, "")
.value("B_KEY_MAP_LOADED", SysMsg::B_KEY_MAP_LOADED, "")
.value("B_LAYOUT_WINDOW", SysMsg::B_LAYOUT_WINDOW, "")
.value("B_MODIFIERS_CHANGED", SysMsg::B_MODIFIERS_CHANGED, "")
.value("B_MINIMIZE", SysMsg::B_MINIMIZE, "")
.value("B_MOUSE_DOWN", SysMsg::B_MOUSE_DOWN, "")
.value("B_MOUSE_MOVED", SysMsg::B_MOUSE_MOVED, "")
.value("B_MOUSE_ENTER_EXIT", SysMsg::B_MOUSE_ENTER_EXIT, "")
.value("B_MOUSE_IDLE", SysMsg::B_MOUSE_IDLE, "")
.value("B_MOUSE_UP", SysMsg::B_MOUSE_UP, "")
.value("B_MOUSE_WHEEL_CHANGED", SysMsg::B_MOUSE_WHEEL_CHANGED, "")
.value("B_OPEN_IN_WORKSPACE", SysMsg::B_OPEN_IN_WORKSPACE, "")
.value("B_PACKAGE_UPDATE", SysMsg::B_PACKAGE_UPDATE, "")
.value("B_PRINTER_CHANGED", SysMsg::B_PRINTER_CHANGED, "")
.value("B_PULSE", SysMsg::B_PULSE, "")
.value("B_READY_TO_RUN", SysMsg::B_READY_TO_RUN, "")
.value("B_REFS_RECEIVED", SysMsg::B_REFS_RECEIVED, "")
.value("B_RELEASE_OVERLAY_LOCK", SysMsg::B_RELEASE_OVERLAY_LOCK, "")
.value("B_ACQUIRE_OVERLAY_LOCK", SysMsg::B_ACQUIRE_OVERLAY_LOCK, "")
.value("B_SCREEN_CHANGED", SysMsg::B_SCREEN_CHANGED, "")
.value("B_VALUE_CHANGED", SysMsg::B_VALUE_CHANGED, "")
.value("B_TRANSLATOR_ADDED", SysMsg::B_TRANSLATOR_ADDED, "")
.value("B_TRANSLATOR_REMOVED", SysMsg::B_TRANSLATOR_REMOVED, "")
.value("B_DELETE_TRANSLATOR", SysMsg::B_DELETE_TRANSLATOR, "")
.value("B_VIEW_MOVED", SysMsg::B_VIEW_MOVED, "")
.value("B_VIEW_RESIZED", SysMsg::B_VIEW_RESIZED, "")
.value("B_WINDOW_MOVED", SysMsg::B_WINDOW_MOVED, "")
.value("B_WINDOW_RESIZED", SysMsg::B_WINDOW_RESIZED, "")
.value("B_WORKSPACES_CHANGED", SysMsg::B_WORKSPACES_CHANGED, "")
.value("B_WORKSPACE_ACTIVATED", SysMsg::B_WORKSPACE_ACTIVATED, "")
.value("B_ZOOM", SysMsg::B_ZOOM, "")
.value("B_COLORS_UPDATED", SysMsg::B_COLORS_UPDATED, "")
.value("B_FONTS_UPDATED", SysMsg::B_FONTS_UPDATED, "")
.value("B_TRACKER_ADDON_MESSAGE", SysMsg::B_TRACKER_ADDON_MESSAGE, "")
.value("_APP_MENU_", SysMsg::_APP_MENU_, "")
.value("_BROWSER_MENUS_", SysMsg::_BROWSER_MENUS_, "")
.value("_MENU_EVENT_", SysMsg::_MENU_EVENT_, "")
.value("_PING_", SysMsg::_PING_, "")
.value("_QUIT_", SysMsg::_QUIT_, "")
.value("_VOLUME_MOUNTED_", SysMsg::_VOLUME_MOUNTED_, "")
.value("_VOLUME_UNMOUNTED_", SysMsg::_VOLUME_UNMOUNTED_, "")
.value("_MESSAGE_DROPPED_", SysMsg::_MESSAGE_DROPPED_, "")
.value("_DISPOSE_DRAG_", SysMsg::_DISPOSE_DRAG_, "")
.value("_MENUS_DONE_", SysMsg::_MENUS_DONE_, "")
.value("_SHOW_DRAG_HANDLES_", SysMsg::_SHOW_DRAG_HANDLES_, "")
.value("_EVENTS_PENDING_", SysMsg::_EVENTS_PENDING_, "")
.value("_UPDATE_", SysMsg::_UPDATE_, "")
.value("_UPDATE_IF_NEEDED_", SysMsg::_UPDATE_IF_NEEDED_, "")
.value("_PRINTER_INFO_", SysMsg::_PRINTER_INFO_, "")
.value("_SETUP_PRINTER_", SysMsg::_SETUP_PRINTER_, "")
.value("_SELECT_PRINTER_", SysMsg::_SELECT_PRINTER_, "")
.export_values();

py::enum_<OMsg>(m, "OMsg", "")
.value("B_SET_PROPERTY", OMsg::B_SET_PROPERTY, "")
.value("B_GET_PROPERTY", OMsg::B_GET_PROPERTY, "")
.value("B_CREATE_PROPERTY", OMsg::B_CREATE_PROPERTY, "")
.value("B_DELETE_PROPERTY", OMsg::B_DELETE_PROPERTY, "")
.value("B_COUNT_PROPERTIES", OMsg::B_COUNT_PROPERTIES, "")
.value("B_EXECUTE_PROPERTY", OMsg::B_EXECUTE_PROPERTY, "")
.value("B_GET_SUPPORTED_SUITES", OMsg::B_GET_SUPPORTED_SUITES, "")
.value("B_UNDO", OMsg::B_UNDO, "")
.value("B_REDO", OMsg::B_REDO, "")
.value("B_CUT", OMsg::B_CUT, "")
.value("B_COPY", OMsg::B_COPY, "")
.value("B_PASTE", OMsg::B_PASTE, "")
.value("B_SELECT_ALL", OMsg::B_SELECT_ALL, "")
.value("B_SAVE_REQUESTED", OMsg::B_SAVE_REQUESTED, "")
.value("B_MESSAGE_NOT_UNDERSTOOD", OMsg::B_MESSAGE_NOT_UNDERSTOOD, "")
.value("B_NO_REPLY", OMsg::B_NO_REPLY, "")
.value("B_REPLY", OMsg::B_REPLY, "")
.value("B_SIMPLE_DATA", OMsg::B_SIMPLE_DATA, "")
.value("B_MIME_DATA", OMsg::B_MIME_DATA, "")
.value("B_ARCHIVED_OBJECT", OMsg::B_ARCHIVED_OBJECT, "")
.value("B_UPDATE_STATUS_BAR", OMsg::B_UPDATE_STATUS_BAR, "")
.value("B_RESET_STATUS_BAR", OMsg::B_RESET_STATUS_BAR, "")
.value("B_NODE_MONITOR", OMsg::B_NODE_MONITOR, "")
.value("B_QUERY_UPDATE", OMsg::B_QUERY_UPDATE, "")
.value("B_ENDORSABLE", OMsg::B_ENDORSABLE, "")
.value("B_COPY_TARGET", OMsg::B_COPY_TARGET, "")
.value("B_MOVE_TARGET", OMsg::B_MOVE_TARGET, "")
.value("B_TRASH_TARGET", OMsg::B_TRASH_TARGET, "")
.value("B_LINK_TARGET", OMsg::B_LINK_TARGET, "")
.value("B_INPUT_DEVICES_CHANGED", OMsg::B_INPUT_DEVICES_CHANGED, "")
.value("B_INPUT_METHOD_EVENT", OMsg::B_INPUT_METHOD_EVENT, "")
.value("B_WINDOW_MOVE_TO", OMsg::B_WINDOW_MOVE_TO, "")
.value("B_WINDOW_MOVE_BY", OMsg::B_WINDOW_MOVE_BY, "")
.value("B_SILENT_RELAUNCH", OMsg::B_SILENT_RELAUNCH, "")
.value("B_OBSERVER_NOTICE_CHANGE", OMsg::B_OBSERVER_NOTICE_CHANGE, "")
.value("B_CONTROL_INVOKED", OMsg::B_CONTROL_INVOKED, "")
.value("B_CONTROL_MODIFIED", OMsg::B_CONTROL_MODIFIED, "")
.export_values();


}
