#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include <pybind11/operators.h>

#include <support/Errors.h>

namespace py = pybind11;


void define_Errors(py::module_& m)
{
m.def("_to_positive_error", &_to_positive_error, "", py::arg("error"));
m.def("_to_negative_error", &_to_negative_error, "", py::arg("error"));
}
PYBIND11_MODULE(Errors,m)
{
m.attr("B_GENERAL_ERROR_BASE") = B_GENERAL_ERROR_BASE;
m.attr("B_OS_ERROR_BASE") = B_OS_ERROR_BASE;
m.attr("B_APP_ERROR_BASE") = B_APP_ERROR_BASE;
m.attr("B_INTERFACE_ERROR_BASE") = B_INTERFACE_ERROR_BASE;
m.attr("B_MEDIA_ERROR_BASE") = B_MEDIA_ERROR_BASE;
m.attr("B_TRANSLATION_ERROR_BASE") = B_TRANSLATION_ERROR_BASE;
m.attr("B_MIDI_ERROR_BASE") = B_MIDI_ERROR_BASE;
m.attr("B_STORAGE_ERROR_BASE") = B_STORAGE_ERROR_BASE;
m.attr("B_POSIX_ERROR_BASE") = B_POSIX_ERROR_BASE;
m.attr("B_MAIL_ERROR_BASE") = B_MAIL_ERROR_BASE;
m.attr("B_PRINT_ERROR_BASE") = B_PRINT_ERROR_BASE;
m.attr("B_DEVICE_ERROR_BASE") = B_DEVICE_ERROR_BASE;
m.attr("B_ERRORS_END") = B_ERRORS_END;
m.attr("B_NO_MEMORY") = B_NO_MEMORY;
m.attr("B_IO_ERROR") = B_IO_ERROR;
m.attr("B_PERMISSION_DENIED") = B_PERMISSION_DENIED;
m.attr("B_BAD_INDEX") = B_BAD_INDEX;
m.attr("B_BAD_TYPE") = B_BAD_TYPE;
m.attr("B_BAD_VALUE") = B_BAD_VALUE;
m.attr("B_MISMATCHED_VALUES") = B_MISMATCHED_VALUES;
m.attr("B_NAME_NOT_FOUND") = B_NAME_NOT_FOUND;
m.attr("B_NAME_IN_USE") = B_NAME_IN_USE;
m.attr("B_TIMED_OUT") = B_TIMED_OUT;
m.attr("B_INTERRUPTED") = B_INTERRUPTED;
m.attr("B_WOULD_BLOCK") = B_WOULD_BLOCK;
m.attr("B_CANCELED") = B_CANCELED;
m.attr("B_NO_INIT") = B_NO_INIT;
m.attr("B_NOT_INITIALIZED") = B_NOT_INITIALIZED;
m.attr("B_BUSY") = B_BUSY;
m.attr("B_NOT_ALLOWED") = B_NOT_ALLOWED;
m.attr("B_BAD_DATA") = B_BAD_DATA;
m.attr("B_DONT_DO_THAT") = B_DONT_DO_THAT;
m.attr("B_ERROR") = B_ERROR;
m.attr("B_OK") = B_OK;
m.attr("B_NO_ERROR") = B_NO_ERROR;
/* Kernel Kit Errors */
m.attr("B_BAD_SEM_ID") = B_BAD_SEM_ID;
m.attr("B_NO_MORE_SEMS") = B_NO_MORE_SEMS;
m.attr("B_BAD_THREAD_ID") = B_BAD_THREAD_ID;
m.attr("B_NO_MORE_THREADS") = B_NO_MORE_THREADS;
m.attr("B_BAD_THREAD_STATE") = B_BAD_THREAD_STATE;
m.attr("B_BAD_TEAM_ID") = B_BAD_TEAM_ID;
m.attr("B_NO_MORE_TEAMS") = B_NO_MORE_TEAMS;
m.attr("B_BAD_PORT_ID") = B_BAD_PORT_ID;
m.attr("B_NO_MORE_PORTS") = B_NO_MORE_PORTS;
m.attr("B_BAD_IMAGE_ID") = B_BAD_IMAGE_ID;
m.attr("B_BAD_ADDRESS") = B_BAD_ADDRESS;
m.attr("B_NOT_AN_EXECUTABLE") = B_NOT_AN_EXECUTABLE;
m.attr("B_MISSING_LIBRARY") = B_MISSING_LIBRARY;
m.attr("B_MISSING_SYMBOL") = B_MISSING_SYMBOL;
m.attr("B_UNKNOWN_EXECUTABLE") = B_UNKNOWN_EXECUTABLE;
m.attr("B_LEGACY_EXECUTABLE") = B_LEGACY_EXECUTABLE;
m.attr("B_DEBUGGER_ALREADY_INSTALLED") = B_DEBUGGER_ALREADY_INSTALLED;
/* Application Kit Errors */
m.attr("B_BAD_REPLY") = B_BAD_REPLY;
m.attr("B_DUPLICATE_REPLY") = B_DUPLICATE_REPLY;
m.attr("B_MESSAGE_TO_SELF") = B_MESSAGE_TO_SELF;
m.attr("B_BAD_HANDLER") = B_BAD_HANDLER;
m.attr("B_ALREADY_RUNNING") = B_ALREADY_RUNNING;
m.attr("B_LAUNCH_FAILED") = B_LAUNCH_FAILED;
m.attr("B_AMBIGUOUS_APP_LAUNCH") = B_AMBIGUOUS_APP_LAUNCH;
m.attr("B_UNKNOWN_MIME_TYPE") = B_UNKNOWN_MIME_TYPE;
m.attr("B_BAD_SCRIPT_SYNTAX") = B_BAD_SCRIPT_SYNTAX;
m.attr("B_LAUNCH_FAILED_NO_RESOLVE_LINK") = B_LAUNCH_FAILED_NO_RESOLVE_LINK;
m.attr("B_LAUNCH_FAILED_EXECUTABLE") = B_LAUNCH_FAILED_EXECUTABLE;
m.attr("B_LAUNCH_FAILED_APP_NOT_FOUND") = B_LAUNCH_FAILED_APP_NOT_FOUND;
m.attr("B_LAUNCH_FAILED_APP_IN_TRASH") = B_LAUNCH_FAILED_APP_IN_TRASH;
m.attr("B_LAUNCH_FAILED_NO_PREFERRED_APP") = B_LAUNCH_FAILED_NO_PREFERRED_APP;
m.attr("B_LAUNCH_FAILED_FILES_APP_NOT_FOUND") = B_LAUNCH_FAILED_FILES_APP_NOT_FOUND;
m.attr("B_BAD_MIME_SNIFFER_RULE") = B_BAD_MIME_SNIFFER_RULE;
m.attr("B_NOT_A_MESSAGE") = B_NOT_A_MESSAGE;
m.attr("B_SHUTDOWN_CANCELLED") = B_SHUTDOWN_CANCELLED;
m.attr("B_SHUTTING_DOWN") = B_SHUTTING_DOWN;
/* Storage Kit/File System Errors */
m.attr("B_FILE_ERROR") = B_FILE_ERROR;
m.attr("B_FILE_EXISTS") = B_FILE_EXISTS;
m.attr("B_ENTRY_NOT_FOUND") = B_ENTRY_NOT_FOUND;
m.attr("B_NAME_TOO_LONG") = B_NAME_TOO_LONG;
m.attr("B_NOT_A_DIRECTORY") = B_NOT_A_DIRECTORY;
m.attr("B_DIRECTORY_NOT_EMPTY") = B_DIRECTORY_NOT_EMPTY;
m.attr("B_DEVICE_FULL") = B_DEVICE_FULL;
m.attr("B_READ_ONLY_DEVICE") = B_READ_ONLY_DEVICE;
m.attr("B_IS_A_DIRECTORY") = B_IS_A_DIRECTORY;
m.attr("B_NO_MORE_FDS") = B_NO_MORE_FDS;
m.attr("B_CROSS_DEVICE_LINK") = B_CROSS_DEVICE_LINK;
m.attr("B_LINK_LIMIT") = B_LINK_LIMIT;
m.attr("B_BUSTED_PIPE") = B_BUSTED_PIPE;
m.attr("B_UNSUPPORTED") = B_UNSUPPORTED;
m.attr("B_PARTITION_TOO_SMALL") = B_PARTITION_TOO_SMALL;
m.attr("B_PARTIAL_READ") = B_PARTIAL_READ;
m.attr("B_PARTIAL_WRITE") = B_PARTIAL_WRITE;
/* Posix Errors */
// TODO veder B_USE_POSTIVE_POSIX_ERRORS
m.attr("B_POSIX_ENOMEM") = B_POSIX_ENOMEM;
m.attr("E2BIG") = E2BIG;
m.attr("ECHILD") = ECHILD;
m.attr("EDEADLK") = EDEADLK;
m.attr("EFBIG") = EFBIG;
m.attr("EMLINK") = EMLINK;
m.attr("ENFILE") = ENFILE;
m.attr("ENODEV") = ENODEV;
m.attr("ENOLCK") = ENOLCK;
m.attr("ENOSYS") = ENOSYS;
m.attr("ENOTTY") = ENOTTY;
m.attr("ENXIO") = ENXIO;
m.attr("ESPIPE") = ESPIPE;
m.attr("ESRCH") = ESRCH;
m.attr("EFPOS") = EFPOS;
m.attr("ESIGPARM") = ESIGPARM;
m.attr("EDOM") = EDOM;
m.attr("ERANGE") = ERANGE;
m.attr("EPROTOTYPE") = EPROTOTYPE;
m.attr("EPROTONOSUPPORT") = EPROTONOSUPPORT;
m.attr("EPFNOSUPPORT") = EPFNOSUPPORT;
m.attr("EAFNOSUPPORT") = EAFNOSUPPORT;
m.attr("EADDRINUSE") = EADDRINUSE;
m.attr("EADDRNOTAVAIL") = EADDRNOTAVAIL;
m.attr("ENETDOWN") = ENETDOWN;
m.attr("ENETUNREACH") = ENETUNREACH;
m.attr("ENETRESET") = ENETRESET;
m.attr("ECONNABORTED") = ECONNABORTED;
m.attr("ECONNRESET") = ECONNRESET;
m.attr("EISCONN") = EISCONN;
m.attr("ENOTCONN") = ENOTCONN;
m.attr("ESHUTDOWN") = ESHUTDOWN;
m.attr("ECONNREFUSED") = ECONNREFUSED;
m.attr("EHOSTUNREACH") = EHOSTUNREACH;
m.attr("ENOPROTOOPT") = ENOPROTOOPT;
m.attr("ENOBUFS") = ENOBUFS;
m.attr("EINPROGRESS") = EINPROGRESS;
m.attr("EALREADY") = EALREADY;
m.attr("EILSEQ") = EILSEQ;
m.attr("ENOMSG") = ENOMSG;
m.attr("ESTALE") = ESTALE;
m.attr("EOVERFLOW") = EOVERFLOW;
m.attr("EMSGSIZE") = EMSGSIZE;
m.attr("EOPNOTSUPP") = EOPNOTSUPP;
m.attr("ENOTSOCK") = ENOTSOCK;
m.attr("EHOSTDOWN") = EHOSTDOWN;
m.attr("EBADMSG") = EBADMSG;
m.attr("ECANCELED") = ECANCELED;
m.attr("EDESTADDRREQ") = EDESTADDRREQ;
m.attr("EDQUOT") = EDQUOT;
m.attr("EIDRM") = EIDRM;
m.attr("EMULTIHOP") = EMULTIHOP;
m.attr("ENODATA") = ENODATA;
m.attr("ENOLINK") = ENOLINK;
m.attr("ENOSR") = ENOSR;
m.attr("ENOSTR") = ENOSTR;
m.attr("ENOTSUP") = ENOTSUP;
m.attr("EPROTO") = EPROTO;
m.attr("ETIME") = ETIME;
m.attr("ETXTBSY") = ETXTBSY;
m.attr("ENOATTR") = ENOATTR;
m.attr("ENOTRECOVERABLE") = ENOTRECOVERABLE;
m.attr("EOWNERDEAD") = EOWNERDEAD;
m.attr("ESOCKTNOSUPPORT") = ESOCKTNOSUPPORT;
// TODO: integrare doppia versione di ENOMEM come da Errors.h


/* POSIX errors that can be mapped to BeOS error codes */
m.attr("EACCES") = EACCES;
m.attr("EINTR") = EINTR;
m.attr("EIO") = EIO;
m.attr("EBUSY") = EBUSY;
m.attr("EFAULT") = EFAULT;
m.attr("ETIMEDOUT") = ETIMEDOUT;
m.attr("EAGAIN") = EAGAIN;
m.attr("EWOULDBLOCK") = EWOULDBLOCK;
m.attr("EBADF") = EBADF;
m.attr("EEXIST") = EEXIST;
m.attr("EINVAL") = EINVAL;
m.attr("ENAMETOOLONG") = ENAMETOOLONG;
m.attr("ENOENT") = ENOENT;
m.attr("EPERM") = EPERM;
m.attr("ENOTDIR") = ENOTDIR;
m.attr("EISDIR") = EISDIR;
m.attr("ENOTEMPTY") = ENOTEMPTY;
m.attr("ENOSPC") = ENOSPC;
m.attr("EROFS") = EROFS;
m.attr("EMFILE") = EMFILE;
m.attr("EXDEV") = EXDEV;
m.attr("ELOOP") = ELOOP;
m.attr("ENOEXEC") = ENOEXEC;
m.attr("EPIPE") = EPIPE;
/* new error codes that can be mapped to POSIX errors */
m.attr("B_BUFFER_OVERFLOW") = B_BUFFER_OVERFLOW;
m.attr("B_TOO_MANY_ARGS") = B_TOO_MANY_ARGS;
m.attr("B_FILE_TOO_LARGE") = B_FILE_TOO_LARGE;
m.attr("B_RESULT_NOT_REPRESENTABLE") = B_RESULT_NOT_REPRESENTABLE;
m.attr("B_DEVICE_NOT_FOUND") = B_DEVICE_NOT_FOUND;
m.attr("B_NOT_SUPPORTED") = B_NOT_SUPPORTED;
/* Media Kit Errors */
m.attr("B_STREAM_NOT_FOUND") = B_STREAM_NOT_FOUND;
m.attr("B_SERVER_NOT_FOUND") = B_SERVER_NOT_FOUND;
m.attr("B_RESOURCE_NOT_FOUND") = B_RESOURCE_NOT_FOUND;
m.attr("B_RESOURCE_UNAVAILABLE") = B_RESOURCE_UNAVAILABLE;
m.attr("B_BAD_SUBSCRIBER") = B_BAD_SUBSCRIBER;
m.attr("B_SUBSCRIBER_NOT_ENTERED") = B_SUBSCRIBER_NOT_ENTERED;
m.attr("B_BUFFER_NOT_AVAILABLE") = B_BUFFER_NOT_AVAILABLE;
m.attr("B_LAST_BUFFER_ERROR") = B_LAST_BUFFER_ERROR;
m.attr("B_MEDIA_SYSTEM_FAILURE") = B_MEDIA_SYSTEM_FAILURE;
m.attr("B_MEDIA_BAD_NODE") = B_MEDIA_BAD_NODE;
m.attr("B_MEDIA_NODE_BUSY") = B_MEDIA_NODE_BUSY;
m.attr("B_MEDIA_BAD_FORMAT") = B_MEDIA_BAD_FORMAT;
m.attr("B_MEDIA_BAD_BUFFER") = B_MEDIA_BAD_BUFFER;
m.attr("B_MEDIA_TOO_MANY_NODES") = B_MEDIA_TOO_MANY_NODES;
m.attr("B_MEDIA_TOO_MANY_BUFFERS") = B_MEDIA_TOO_MANY_BUFFERS;
m.attr("B_MEDIA_NODE_ALREADY_EXISTS") = B_MEDIA_NODE_ALREADY_EXISTS;
m.attr("B_MEDIA_BUFFER_ALREADY_EXISTS") = B_MEDIA_BUFFER_ALREADY_EXISTS;
m.attr("B_MEDIA_CANNOT_SEEK") = B_MEDIA_CANNOT_SEEK;
m.attr("B_MEDIA_CANNOT_CHANGE_RUN_MODE") = B_MEDIA_CANNOT_CHANGE_RUN_MODE;
m.attr("B_MEDIA_APP_ALREADY_REGISTERED") = B_MEDIA_APP_ALREADY_REGISTERED;
m.attr("B_MEDIA_APP_NOT_REGISTERED") = B_MEDIA_APP_NOT_REGISTERED;
m.attr("B_MEDIA_CANNOT_RECLAIM_BUFFERS") = B_MEDIA_CANNOT_RECLAIM_BUFFERS;
m.attr("B_MEDIA_BUFFERS_NOT_RECLAIMED") = B_MEDIA_BUFFERS_NOT_RECLAIMED;
m.attr("B_MEDIA_TIME_SOURCE_STOPPED") = B_MEDIA_TIME_SOURCE_STOPPED;
m.attr("B_MEDIA_TIME_SOURCE_BUSY") = B_MEDIA_TIME_SOURCE_BUSY;
m.attr("B_MEDIA_BAD_SOURCE") = B_MEDIA_BAD_SOURCE;
m.attr("B_MEDIA_BAD_DESTINATION") = B_MEDIA_BAD_DESTINATION;
m.attr("B_MEDIA_ALREADY_CONNECTED") = B_MEDIA_ALREADY_CONNECTED;
m.attr("B_MEDIA_NOT_CONNECTED") = B_MEDIA_NOT_CONNECTED;
m.attr("B_MEDIA_BAD_CLIP_FORMAT") = B_MEDIA_BAD_CLIP_FORMAT;
m.attr("B_MEDIA_ADDON_FAILED") = B_MEDIA_ADDON_FAILED;
m.attr("B_MEDIA_ADDON_DISABLED") = B_MEDIA_ADDON_DISABLED;
m.attr("B_MEDIA_CHANGE_IN_PROGRESS") = B_MEDIA_CHANGE_IN_PROGRESS;
m.attr("B_MEDIA_STALE_CHANGE_COUNT") = B_MEDIA_STALE_CHANGE_COUNT;
m.attr("B_MEDIA_ADDON_RESTRICTED") = B_MEDIA_ADDON_RESTRICTED;
m.attr("B_MEDIA_NO_HANDLER") = B_MEDIA_NO_HANDLER;
m.attr("B_MEDIA_DUPLICATE_FORMAT") = B_MEDIA_DUPLICATE_FORMAT;
m.attr("B_MEDIA_REALTIME_DISABLED") = B_MEDIA_REALTIME_DISABLED;
m.attr("B_MEDIA_REALTIME_UNAVAILABLE") = B_MEDIA_REALTIME_UNAVAILABLE;
/* Mail Kit Errors */
m.attr("B_MAIL_NO_DAEMON") = B_MAIL_NO_DAEMON;
m.attr("B_MAIL_UNKNOWN_USER") = B_MAIL_UNKNOWN_USER;
m.attr("B_MAIL_WRONG_PASSWORD") = B_MAIL_WRONG_PASSWORD;
m.attr("B_MAIL_UNKNOWN_HOST") = B_MAIL_UNKNOWN_HOST;
m.attr("B_MAIL_ACCESS_ERROR") = B_MAIL_ACCESS_ERROR;
m.attr("B_MAIL_UNKNOWN_FIELD") = B_MAIL_UNKNOWN_FIELD;
m.attr("B_MAIL_NO_RECIPIENT") = B_MAIL_NO_RECIPIENT;
m.attr("B_MAIL_INVALID_MAIL") = B_MAIL_INVALID_MAIL;
/* Printing Errors */
m.attr("B_NO_PRINT_SERVER") = B_NO_PRINT_SERVER;
/* Device Kit Errors */
m.attr("B_DEV_INVALID_IOCTL") = B_DEV_INVALID_IOCTL;
m.attr("B_DEV_NO_MEMORY") = B_DEV_NO_MEMORY;
m.attr("B_DEV_BAD_DRIVE_NUM") = B_DEV_BAD_DRIVE_NUM;
m.attr("B_DEV_NO_MEDIA") = B_DEV_NO_MEDIA;
m.attr("B_DEV_UNREADABLE") = B_DEV_UNREADABLE;
m.attr("B_DEV_FORMAT_ERROR") = B_DEV_FORMAT_ERROR;
m.attr("B_DEV_TIMEOUT") = B_DEV_TIMEOUT;
m.attr("B_DEV_RECALIBRATE_ERROR") = B_DEV_RECALIBRATE_ERROR;
m.attr("B_DEV_SEEK_ERROR") = B_DEV_SEEK_ERROR;
m.attr("B_DEV_ID_ERROR") = B_DEV_ID_ERROR;
m.attr("B_DEV_READ_ERROR") = B_DEV_READ_ERROR;
m.attr("B_DEV_WRITE_ERROR") = B_DEV_WRITE_ERROR;
m.attr("B_DEV_NOT_READY") = B_DEV_NOT_READY;
m.attr("B_DEV_MEDIA_CHANGED") = B_DEV_MEDIA_CHANGED;
m.attr("B_DEV_MEDIA_CHANGE_REQUESTED") = B_DEV_MEDIA_CHANGE_REQUESTED;
m.attr("B_DEV_RESOURCE_CONFLICT") = B_DEV_RESOURCE_CONFLICT;
m.attr("B_DEV_CONFIGURATION_ERROR") = B_DEV_CONFIGURATION_ERROR;
m.attr("B_DEV_DISABLED_BY_USER") = B_DEV_DISABLED_BY_USER;
m.attr("B_DEV_DOOR_OPEN") = B_DEV_DOOR_OPEN;
m.attr("B_DEV_INVALID_PIPE") = B_DEV_INVALID_PIPE;
m.attr("B_DEV_CRC_ERROR") = B_DEV_CRC_ERROR;
m.attr("B_DEV_STALLED") = B_DEV_STALLED;
m.attr("B_DEV_BAD_PID") = B_DEV_BAD_PID;
m.attr("B_DEV_UNEXPECTED_PID") = B_DEV_UNEXPECTED_PID;
m.attr("B_DEV_DATA_OVERRUN") = B_DEV_DATA_OVERRUN;
m.attr("B_DEV_DATA_UNDERRUN") = B_DEV_DATA_UNDERRUN;
m.attr("B_DEV_FIFO_OVERRUN") = B_DEV_FIFO_OVERRUN;
m.attr("B_DEV_FIFO_UNDERRUN") = B_DEV_FIFO_UNDERRUN;
m.attr("B_DEV_PENDING") = B_DEV_PENDING;
m.attr("B_DEV_MULTIPLE_ERRORS") = B_DEV_MULTIPLE_ERRORS;
m.attr("B_DEV_TOO_LATE") = B_DEV_TOO_LATE;
/* Translation Kit Errors */
m.attr("B_TRANSLATION_BASE_ERROR") = B_TRANSLATION_BASE_ERROR;
m.attr("B_NO_TRANSLATOR") = B_NO_TRANSLATOR;
m.attr("B_ILLEGAL_DATA") = B_ILLEGAL_DATA;
}
