#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include <pybind11/operators.h>

#include <DiskDeviceDefs.h>

namespace py = pybind11;


void define_DiskDeviceDefs(py::module_& m)
{
m.attr("B_PARTITION_IS_DEVICE") = py::cast(B_PARTITION_IS_DEVICE);
m.attr("B_PARTITION_FILE_SYSTEM") = py::cast(B_PARTITION_FILE_SYSTEM);
m.attr("B_PARTITION_PARTITIONING_SYSTEM") = py::cast(B_PARTITION_PARTITIONING_SYSTEM);
m.attr("B_PARTITION_READ_ONLY") = py::cast(B_PARTITION_READ_ONLY);
m.attr("B_PARTITION_MOUNTED") = py::cast(B_PARTITION_MOUNTED);
m.attr("B_PARTITION_BUSY") = py::cast(B_PARTITION_BUSY);

m.attr("B_PARTITION_VALID") = py::cast(B_PARTITION_VALID);
m.attr("B_PARTITION_CORRUPT") = py::cast(B_PARTITION_CORRUPT);
m.attr("B_PARTITION_UNRECOGNIZED") = py::cast(B_PARTITION_UNRECOGNIZED);
m.attr("B_PARTITION_UNINITIALIZED") = py::cast(B_PARTITION_UNINITIALIZED);

m.attr("B_PARTITION_CHANGED_OFFSET") = py::cast(B_PARTITION_CHANGED_OFFSET);
m.attr("B_PARTITION_CHANGED_SIZE") = py::cast(B_PARTITION_CHANGED_SIZE);
m.attr("B_PARTITION_CHANGED_CONTENT_SIZE") = py::cast(B_PARTITION_CHANGED_CONTENT_SIZE);
m.attr("B_PARTITION_CHANGED_BLOCK_SIZE") = py::cast(B_PARTITION_CHANGED_BLOCK_SIZE);
m.attr("B_PARTITION_CHANGED_STATUS") = py::cast(B_PARTITION_CHANGED_STATUS);
m.attr("B_PARTITION_CHANGED_FLAGS") = py::cast(B_PARTITION_CHANGED_FLAGS);
m.attr("B_PARTITION_CHANGED_VOLUME") = py::cast(B_PARTITION_CHANGED_VOLUME);
m.attr("B_PARTITION_CHANGED_NAME") = py::cast(B_PARTITION_CHANGED_NAME);
m.attr("B_PARTITION_CHANGED_CONTENT_NAME") = py::cast(B_PARTITION_CHANGED_CONTENT_NAME);
m.attr("B_PARTITION_CHANGED_TYPE") = py::cast(B_PARTITION_CHANGED_TYPE);
m.attr("B_PARTITION_CHANGED_CONTENT_TYPE") = py::cast(B_PARTITION_CHANGED_CONTENT_TYPE);
m.attr("B_PARTITION_CHANGED_PARAMETERS") = py::cast(B_PARTITION_CHANGED_PARAMETERS);
m.attr("B_PARTITION_CHANGED_CONTENT_PARAMETERS") = py::cast(B_PARTITION_CHANGED_CONTENT_PARAMETERS);
m.attr("B_PARTITION_CHANGED_CHILDREN") = py::cast(B_PARTITION_CHANGED_CHILDREN);
m.attr("B_PARTITION_CHANGED_DESCENDANTS") = py::cast(B_PARTITION_CHANGED_DESCENDANTS);
m.attr("B_PARTITION_CHANGED_DEFRAGMENTATION") = py::cast(B_PARTITION_CHANGED_DEFRAGMENTATION);
m.attr("B_PARTITION_CHANGED_CHECK") = py::cast(B_PARTITION_CHANGED_CHECK);
m.attr("B_PARTITION_CHANGED_REPAIR") = py::cast(B_PARTITION_CHANGED_REPAIR);
m.attr("B_PARTITION_CHANGED_INITIALIZATION") = py::cast(B_PARTITION_CHANGED_INITIALIZATION);

m.attr("B_DISK_DEVICE_REMOVABLE") = py::cast(B_DISK_DEVICE_REMOVABLE);
m.attr("B_DISK_DEVICE_HAS_MEDIA") = py::cast(B_DISK_DEVICE_HAS_MEDIA);
m.attr("B_DISK_DEVICE_READ_ONLY") = py::cast(B_DISK_DEVICE_READ_ONLY);
m.attr("B_DISK_DEVICE_WRITE_ONCE") = py::cast(B_DISK_DEVICE_WRITE_ONCE);
m.attr("B_DISK_DEVICE_IS_FILE") = py::cast(B_DISK_DEVICE_IS_FILE);

m.attr("B_DISK_SYSTEM_IS_FILE_SYSTEM") = py::cast(B_DISK_SYSTEM_IS_FILE_SYSTEM);
m.attr("B_DISK_SYSTEM_SUPPORTS_CHECKING") = py::cast(B_DISK_SYSTEM_SUPPORTS_CHECKING);
m.attr("B_DISK_SYSTEM_SUPPORTS_REPAIRING") = py::cast(B_DISK_SYSTEM_SUPPORTS_REPAIRING);
m.attr("B_DISK_SYSTEM_SUPPORTS_RESIZING") = py::cast(B_DISK_SYSTEM_SUPPORTS_RESIZING);
m.attr("B_DISK_SYSTEM_SUPPORTS_MOVING") = py::cast(B_DISK_SYSTEM_SUPPORTS_MOVING);
m.attr("B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_NAME") = py::cast(B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_NAME);
m.attr("B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_PARAMETERS") = py::cast(B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_PARAMETERS);
m.attr("B_DISK_SYSTEM_SUPPORTS_INITIALIZING") = py::cast(B_DISK_SYSTEM_SUPPORTS_INITIALIZING);
m.attr("B_DISK_SYSTEM_SUPPORTS_CONTENT_NAME") = py::cast(B_DISK_SYSTEM_SUPPORTS_CONTENT_NAME);
m.attr("B_DISK_SYSTEM_SUPPORTS_DEFRAGMENTING") = py::cast(B_DISK_SYSTEM_SUPPORTS_DEFRAGMENTING);
m.attr("B_DISK_SYSTEM_SUPPORTS_DEFRAGMENTING_WHILE_MOUNTED") = py::cast(B_DISK_SYSTEM_SUPPORTS_DEFRAGMENTING_WHILE_MOUNTED);
m.attr("B_DISK_SYSTEM_SUPPORTS_CHECKING_WHILE_MOUNTED") = py::cast(B_DISK_SYSTEM_SUPPORTS_CHECKING_WHILE_MOUNTED);
m.attr("B_DISK_SYSTEM_SUPPORTS_REPAIRING_WHILE_MOUNTED") = py::cast(B_DISK_SYSTEM_SUPPORTS_REPAIRING_WHILE_MOUNTED);
m.attr("B_DISK_SYSTEM_SUPPORTS_RESIZING_WHILE_MOUNTED") = py::cast(B_DISK_SYSTEM_SUPPORTS_RESIZING_WHILE_MOUNTED);
m.attr("B_DISK_SYSTEM_SUPPORTS_MOVING_WHILE_MOUNTED") = py::cast(B_DISK_SYSTEM_SUPPORTS_MOVING_WHILE_MOUNTED);
m.attr("B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_NAME_WHILE_MOUNTED") = py::cast(B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_NAME_WHILE_MOUNTED);
m.attr("B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_PARAMETERS_WHILE_MOUNTED") = py::cast(B_DISK_SYSTEM_SUPPORTS_SETTING_CONTENT_PARAMETERS_WHILE_MOUNTED);
m.attr("B_DISK_SYSTEM_SUPPORTS_WRITING") = py::cast(B_DISK_SYSTEM_SUPPORTS_WRITING);
m.attr("B_DISK_SYSTEM_SUPPORTS_RESIZING_CHILD") = py::cast(B_DISK_SYSTEM_SUPPORTS_RESIZING_CHILD);
m.attr("B_DISK_SYSTEM_SUPPORTS_MOVING_CHILD") = py::cast(B_DISK_SYSTEM_SUPPORTS_MOVING_CHILD);
m.attr("B_DISK_SYSTEM_SUPPORTS_SETTING_NAME") = py::cast(B_DISK_SYSTEM_SUPPORTS_SETTING_NAME);
m.attr("B_DISK_SYSTEM_SUPPORTS_SETTING_TYPE") = py::cast(B_DISK_SYSTEM_SUPPORTS_SETTING_TYPE);
m.attr("B_DISK_SYSTEM_SUPPORTS_SETTING_PARAMETERS") = py::cast(B_DISK_SYSTEM_SUPPORTS_SETTING_PARAMETERS);
m.attr("B_DISK_SYSTEM_SUPPORTS_CREATING_CHILD") = py::cast(B_DISK_SYSTEM_SUPPORTS_CREATING_CHILD);
m.attr("B_DISK_SYSTEM_SUPPORTS_DELETING_CHILD") = py::cast(B_DISK_SYSTEM_SUPPORTS_DELETING_CHILD);
m.attr("B_DISK_SYSTEM_SUPPORTS_NAME") = py::cast(B_DISK_SYSTEM_SUPPORTS_NAME);

m.attr("B_DISK_DEVICE_JOB_BAD_TYPE") = py::cast(B_DISK_DEVICE_JOB_BAD_TYPE);
m.attr("B_DISK_DEVICE_JOB_DEFRAGMENT") = py::cast(B_DISK_DEVICE_JOB_DEFRAGMENT);
m.attr("B_DISK_DEVICE_JOB_REPAIR") = py::cast(B_DISK_DEVICE_JOB_REPAIR);
m.attr("B_DISK_DEVICE_JOB_RESIZE") = py::cast(B_DISK_DEVICE_JOB_RESIZE);
m.attr("B_DISK_DEVICE_JOB_MOVE") = py::cast(B_DISK_DEVICE_JOB_MOVE);
m.attr("B_DISK_DEVICE_JOB_SET_NAME") = py::cast(B_DISK_DEVICE_JOB_SET_NAME);
m.attr("B_DISK_DEVICE_JOB_SET_CONTENT_NAME") = py::cast(B_DISK_DEVICE_JOB_SET_CONTENT_NAME);
m.attr("B_DISK_DEVICE_JOB_SET_TYPE") = py::cast(B_DISK_DEVICE_JOB_SET_TYPE);
m.attr("B_DISK_DEVICE_JOB_SET_PARAMETERS") = py::cast(B_DISK_DEVICE_JOB_SET_PARAMETERS);
m.attr("B_DISK_DEVICE_JOB_SET_CONTENT_PARAMETERS") = py::cast(B_DISK_DEVICE_JOB_SET_CONTENT_PARAMETERS);
m.attr("B_DISK_DEVICE_JOB_INITIALIZE") = py::cast(B_DISK_DEVICE_JOB_INITIALIZE);
m.attr("B_DISK_DEVICE_JOB_UNINITIALIZE") = py::cast(B_DISK_DEVICE_JOB_UNINITIALIZE);
m.attr("B_DISK_DEVICE_JOB_CREATE") = py::cast(B_DISK_DEVICE_JOB_CREATE);
m.attr("B_DISK_DEVICE_JOB_DELETE") = py::cast(B_DISK_DEVICE_JOB_DELETE);
m.attr("B_DISK_DEVICE_JOB_SCAN") = py::cast(B_DISK_DEVICE_JOB_SCAN);

m.attr("B_DISK_DEVICE_JOB_UNINITIALIZED") = py::cast(B_DISK_DEVICE_JOB_UNINITIALIZED);
m.attr("B_DISK_DEVICE_JOB_SCHEDULED") = py::cast(B_DISK_DEVICE_JOB_SCHEDULED);
m.attr("B_DISK_DEVICE_JOB_IN_PROGRESS") = py::cast(B_DISK_DEVICE_JOB_IN_PROGRESS);
m.attr("B_DISK_DEVICE_JOB_SUCCEEDED") = py::cast(B_DISK_DEVICE_JOB_SUCCEEDED);
m.attr("B_DISK_DEVICE_JOB_FAILED") = py::cast(B_DISK_DEVICE_JOB_FAILED);
m.attr("B_DISK_DEVICE_JOB_CANCELED") = py::cast(B_DISK_DEVICE_JOB_CANCELED);

m.attr("B_DISK_DEVICE_JOB_CAN_CANCEL") = py::cast(B_DISK_DEVICE_JOB_CAN_CANCEL);
m.attr("B_DISK_DEVICE_JOB_STOP_ON_CANCEL") = py::cast(B_DISK_DEVICE_JOB_STOP_ON_CANCEL);
m.attr("B_DISK_DEVICE_JOB_REVERSE_ON_CANCEL") = py::cast(B_DISK_DEVICE_JOB_REVERSE_ON_CANCEL);
m.attr("B_DISK_DEVICE_JOB_CAN_PAUSE") = py::cast(B_DISK_DEVICE_JOB_CAN_PAUSE);

py::enum_<B_PARAMETER_EDITOR_TYPE>(m, "B_PARAMETER_EDITOR_TYPE", "")
.value("B_CREATE_PARAMETER_EDITOR", B_PARAMETER_EDITOR_TYPE::B_CREATE_PARAMETER_EDITOR, "")
.value("B_INITIALIZE_PARAMETER_EDITOR", B_PARAMETER_EDITOR_TYPE::B_INITIALIZE_PARAMETER_EDITOR, "")
.value("B_DELETE_PARAMETER_EDITOR", B_PARAMETER_EDITOR_TYPE::B_DELETE_PARAMETER_EDITOR, "")
.value("B_PROPERTIES_PARAMETER_EDITOR", B_PARAMETER_EDITOR_TYPE::B_PROPERTIES_PARAMETER_EDITOR, "")
.export_values();

py::class_<disk_device_job_progress_info>(m, "disk_device_job_progress_info")
.def_readwrite("status", &disk_device_job_progress_info::status, "")
.def_readwrite("interrupt_properties", &disk_device_job_progress_info::interrupt_properties, "")
.def_readwrite("task_count", &disk_device_job_progress_info::task_count, "")
.def_readwrite("completed_tasks", &disk_device_job_progress_info::completed_tasks, "")
.def_readwrite("current_task_progress", &disk_device_job_progress_info::current_task_progress, "")
.def_readwrite("current_task_description", &disk_device_job_progress_info::current_task_description, "")
;


}
