#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include <pybind11/operators.h>

#include <FindDirectory.h>
#include <Volume.h>
#include <Path.h>

namespace py = pybind11;


PYBIND11_MODULE(FindDirectory, m)
{
/*
py::enum_<directory_which>(m, "directory_which", "")
.value("B_DESKTOP_DIRECTORY",0, "")
.value("B_TRASH_DIRECTORY", 1, "")
.value("B_SYSTEM_DIRECTORY", 1000, "")
.value("B_SYSTEM_ADDONS_DIRECTORY", 1002, "")
.value("B_SYSTEM_BOOT_DIRECTORY", 1003, "")
.value("B_SYSTEM_FONTS_DIRECTORY", 1004, "")
.value("B_SYSTEM_LIB_DIRECTORY", 1005, "")
.value("B_SYSTEM_SERVERS_DIRECTORY", 1006, "")
.value("B_SYSTEM_APPS_DIRECTORY", 1007, "")
.value("B_SYSTEM_BIN_DIRECTORY", 1008, "")
.value("B_SYSTEM_DOCUMENTATION_DIRECTORY", 1010, "")
.value("B_SYSTEM_PREFERENCES_DIRECTORY", 1011, "")
.value("B_SYSTEM_TRANSLATORS_DIRECTORY", 1012, "")
.value("B_SYSTEM_MEDIA_NODES_DIRECTORY", 1013, "")
.value("B_SYSTEM_SOUNDS_DIRECTORY", 1014, "")
.value("B_SYSTEM_DATA_DIRECTORY", 1015, "")
.value("B_SYSTEM_DEVELOP_DIRECTORY", 1016, "")
.value("B_SYSTEM_PACKAGES_DIRECTORY", 1017, "")
.value("B_SYSTEM_HEADERS_DIRECTORY", 1018, "")
.value("B_SYSTEM_ETC_DIRECTORY", 2008, "")
.value("B_SYSTEM_SETTINGS_DIRECTORY", 2010, "")
.value("B_SYSTEM_LOG_DIRECTORY", 2012, "")
.value("B_SYSTEM_SPOOL_DIRECTORY", 2013, "")
.value("B_SYSTEM_TEMP_DIRECTORY", 2014, "")
.value("B_SYSTEM_VAR_DIRECTORY", 2015, "")
.value("B_SYSTEM_CACHE_DIRECTORY", 2020, "")
.value("B_SYSTEM_NONPACKAGED_DIRECTORY", 2023, "")
.value("B_SYSTEM_NONPACKAGED_ADDONS_DIRECTORY", 2024, "")
.value("B_SYSTEM_NONPACKAGED_TRANSLATORS_DIRECTORY", 2025, "")
.value("B_SYSTEM_NONPACKAGED_MEDIA_NODES_DIRECTORY", 2026, "")
.value("B_SYSTEM_NONPACKAGED_BIN_DIRECTORY", 2027, "")
.value("B_SYSTEM_NONPACKAGED_DATA_DIRECTORY", 2028, "")
.value("B_SYSTEM_NONPACKAGED_FONTS_DIRECTORY", 2029, "")
.value("B_SYSTEM_NONPACKAGED_SOUNDS_DIRECTORY", 2030, "")
.value("B_SYSTEM_NONPACKAGED_DOCUMENTATION_DIRECTORY", 2031, "")
.value("B_SYSTEM_NONPACKAGED_LIB_DIRECTORY", 2032, "")
.value("B_SYSTEM_NONPACKAGED_HEADERS_DIRECTORY", 2033, "")
.value("B_SYSTEM_NONPACKAGED_DEVELOP_DIRECTORY", 2034, "")
.value("B_USER_DIRECTORY", 3000, "")
.value("B_USER_CONFIG_DIRECTORY", 3001, "")
.value("B_USER_ADDONS_DIRECTORY", 3002, "")
.value("B_USER_BOOT_DIRECTORY", 3003, "")
.value("B_USER_FONTS_DIRECTORY", 3004, "")
.value("B_USER_LIB_DIRECTORY", 3005, "")
.value("B_USER_SETTINGS_DIRECTORY", 3006, "")
.value("B_USER_DESKBAR_DIRECTORY", 3007, "")
.value("B_USER_PRINTERS_DIRECTORY", 3008, "")
.value("B_USER_TRANSLATORS_DIRECTORY", 3009, "")
.value("B_USER_MEDIA_NODES_DIRECTORY", 3010, "")
.value("B_USER_SOUNDS_DIRECTORY", 3011, "")
.value("B_USER_DATA_DIRECTORY", 3012, "")
.value("B_USER_CACHE_DIRECTORY", 3013, "")
.value("B_USER_PACKAGES_DIRECTORY", 3014, "")
.value("B_USER_HEADERS_DIRECTORY", 3015, "")
.value("B_USER_NONPACKAGED_DIRECTORY", 3016, "")
.value("B_USER_NONPACKAGED_ADDONS_DIRECTORY", 3017, "")
.value("B_USER_NONPACKAGED_TRANSLATORS_DIRECTORY", 3018, "")
.value("B_USER_NONPACKAGED_MEDIA_NODES_DIRECTORY", 3019, "")
.value("B_USER_NONPACKAGED_BIN_DIRECTORY", 3020, "")
.value("B_USER_NONPACKAGED_DATA_DIRECTORY", 3021, "")
.value("B_USER_NONPACKAGED_FONTS_DIRECTORY", 3022, "")
.value("B_USER_NONPACKAGED_SOUNDS_DIRECTORY", 3023, "")
.value("B_USER_NONPACKAGED_DOCUMENTATION_DIRECTORY", 3024, "")
.value("B_USER_NONPACKAGED_LIB_DIRECTORY", 3025, "")
.value("B_USER_NONPACKAGED_HEADERS_DIRECTORY", 3026, "")
.value("B_USER_NONPACKAGED_DEVELOP_DIRECTORY", 3027, "")
.value("B_USER_DEVELOP_DIRECTORY", 3028, "")
.value("B_USER_DOCUMENTATION_DIRECTORY", 3029, "")
.value("B_USER_SERVERS_DIRECTORY", 3030, "")
.value("B_USER_APPS_DIRECTORY", 3031, "")
.value("B_USER_BIN_DIRECTORY", 3032, "")
.value("B_USER_PREFERENCES_DIRECTORY", 3033, "")
.value("B_USER_ETC_DIRECTORY", 3034, "")
.value("B_USER_LOG_DIRECTORY", 3035, "")
.value("B_USER_SPOOL_DIRECTORY", 3036, "")
.value("B_USER_VAR_DIRECTORY", 3037, "")
.value("B_APPS_DIRECTORY", 4000, "")
.value("B_PREFERENCES_DIRECTORY", 4001, "")
.value("B_UTILITIES_DIRECTORY", 4002, "")
.value("B_PACKAGE_LINKS_DIRECTORY", 4003, "")
.value("B_BEOS_DIRECTORY", 1000, "")
.value("B_BEOS_SYSTEM_DIRECTORY", 1001, "")
.value("B_BEOS_ADDONS_DIRECTORY", 1002, "")
.value("B_BEOS_BOOT_DIRECTORY", 1003, "")
.value("B_BEOS_FONTS_DIRECTORY", 1004, "")
.value("B_BEOS_LIB_DIRECTORY", 1005, "")
.value("B_BEOS_SERVERS_DIRECTORY", 1006, "")
.value("B_BEOS_APPS_DIRECTORY", 1007, "")
.value("B_BEOS_BIN_DIRECTORY", 1008, "")
.value("B_BEOS_ETC_DIRECTORY", 1009, "")
.value("B_BEOS_DOCUMENTATION_DIRECTORY", 1010, "")
.value("B_BEOS_PREFERENCES_DIRECTORY", 1011, "")
.value("B_BEOS_TRANSLATORS_DIRECTORY", 1012, "")
.value("B_BEOS_MEDIA_NODES_DIRECTORY", 1013, "")
.value("B_BEOS_SOUNDS_DIRECTORY", 1014, "")
.export_values();*/


py::enum_<directory_which>(m, "directory_which", "")
.value("B_DESKTOP_DIRECTORY", directory_which::B_DESKTOP_DIRECTORY, "")
.value("B_TRASH_DIRECTORY", directory_which::B_TRASH_DIRECTORY, "")
.value("B_SYSTEM_DIRECTORY", directory_which::B_SYSTEM_DIRECTORY, "")
.value("B_SYSTEM_ADDONS_DIRECTORY", directory_which::B_SYSTEM_ADDONS_DIRECTORY, "")
.value("B_SYSTEM_BOOT_DIRECTORY", directory_which::B_SYSTEM_BOOT_DIRECTORY, "")
.value("B_SYSTEM_FONTS_DIRECTORY", directory_which::B_SYSTEM_FONTS_DIRECTORY, "")
.value("B_SYSTEM_LIB_DIRECTORY", directory_which::B_SYSTEM_LIB_DIRECTORY, "")
.value("B_SYSTEM_SERVERS_DIRECTORY", directory_which::B_SYSTEM_SERVERS_DIRECTORY, "")
.value("B_SYSTEM_APPS_DIRECTORY", directory_which::B_SYSTEM_APPS_DIRECTORY, "")
.value("B_SYSTEM_BIN_DIRECTORY", directory_which::B_SYSTEM_BIN_DIRECTORY, "")
.value("B_SYSTEM_DOCUMENTATION_DIRECTORY", directory_which::B_SYSTEM_DOCUMENTATION_DIRECTORY, "")
.value("B_SYSTEM_PREFERENCES_DIRECTORY", directory_which::B_SYSTEM_PREFERENCES_DIRECTORY, "")
.value("B_SYSTEM_TRANSLATORS_DIRECTORY", directory_which::B_SYSTEM_TRANSLATORS_DIRECTORY, "")
.value("B_SYSTEM_MEDIA_NODES_DIRECTORY", directory_which::B_SYSTEM_MEDIA_NODES_DIRECTORY, "")
.value("B_SYSTEM_SOUNDS_DIRECTORY", directory_which::B_SYSTEM_SOUNDS_DIRECTORY, "")
.value("B_SYSTEM_DATA_DIRECTORY", directory_which::B_SYSTEM_DATA_DIRECTORY, "")
.value("B_SYSTEM_DEVELOP_DIRECTORY", directory_which::B_SYSTEM_DEVELOP_DIRECTORY, "")
.value("B_SYSTEM_PACKAGES_DIRECTORY", directory_which::B_SYSTEM_PACKAGES_DIRECTORY, "")
.value("B_SYSTEM_HEADERS_DIRECTORY", directory_which::B_SYSTEM_HEADERS_DIRECTORY, "")
.value("B_SYSTEM_ETC_DIRECTORY", directory_which::B_SYSTEM_ETC_DIRECTORY, "")
.value("B_SYSTEM_SETTINGS_DIRECTORY", directory_which::B_SYSTEM_SETTINGS_DIRECTORY, "")
.value("B_SYSTEM_LOG_DIRECTORY", directory_which::B_SYSTEM_LOG_DIRECTORY, "")
.value("B_SYSTEM_SPOOL_DIRECTORY", directory_which::B_SYSTEM_SPOOL_DIRECTORY, "")
.value("B_SYSTEM_TEMP_DIRECTORY", directory_which::B_SYSTEM_TEMP_DIRECTORY, "")
.value("B_SYSTEM_VAR_DIRECTORY", directory_which::B_SYSTEM_VAR_DIRECTORY, "")
.value("B_SYSTEM_CACHE_DIRECTORY", directory_which::B_SYSTEM_CACHE_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_ADDONS_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_ADDONS_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_TRANSLATORS_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_TRANSLATORS_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_MEDIA_NODES_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_MEDIA_NODES_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_BIN_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_BIN_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_DATA_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_DATA_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_FONTS_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_FONTS_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_SOUNDS_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_SOUNDS_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_DOCUMENTATION_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_DOCUMENTATION_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_LIB_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_LIB_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_HEADERS_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_HEADERS_DIRECTORY, "")
.value("B_SYSTEM_NONPACKAGED_DEVELOP_DIRECTORY", directory_which::B_SYSTEM_NONPACKAGED_DEVELOP_DIRECTORY, "")
.value("B_USER_DIRECTORY", directory_which::B_USER_DIRECTORY, "")
.value("B_USER_CONFIG_DIRECTORY", directory_which::B_USER_CONFIG_DIRECTORY, "")
.value("B_USER_ADDONS_DIRECTORY", directory_which::B_USER_ADDONS_DIRECTORY, "")
.value("B_USER_BOOT_DIRECTORY", directory_which::B_USER_BOOT_DIRECTORY, "")
.value("B_USER_FONTS_DIRECTORY", directory_which::B_USER_FONTS_DIRECTORY, "")
.value("B_USER_LIB_DIRECTORY", directory_which::B_USER_LIB_DIRECTORY, "")
.value("B_USER_SETTINGS_DIRECTORY", directory_which::B_USER_SETTINGS_DIRECTORY, "")
.value("B_USER_DESKBAR_DIRECTORY", directory_which::B_USER_DESKBAR_DIRECTORY, "")
.value("B_USER_PRINTERS_DIRECTORY", directory_which::B_USER_PRINTERS_DIRECTORY, "")
.value("B_USER_TRANSLATORS_DIRECTORY", directory_which::B_USER_TRANSLATORS_DIRECTORY, "")
.value("B_USER_MEDIA_NODES_DIRECTORY", directory_which::B_USER_MEDIA_NODES_DIRECTORY, "")
.value("B_USER_SOUNDS_DIRECTORY", directory_which::B_USER_SOUNDS_DIRECTORY, "")
.value("B_USER_DATA_DIRECTORY", directory_which::B_USER_DATA_DIRECTORY, "")
.value("B_USER_CACHE_DIRECTORY", directory_which::B_USER_CACHE_DIRECTORY, "")
.value("B_USER_PACKAGES_DIRECTORY", directory_which::B_USER_PACKAGES_DIRECTORY, "")
.value("B_USER_HEADERS_DIRECTORY", directory_which::B_USER_HEADERS_DIRECTORY, "")
.value("B_USER_NONPACKAGED_DIRECTORY", directory_which::B_USER_NONPACKAGED_DIRECTORY, "")
.value("B_USER_NONPACKAGED_ADDONS_DIRECTORY", directory_which::B_USER_NONPACKAGED_ADDONS_DIRECTORY, "")
.value("B_USER_NONPACKAGED_TRANSLATORS_DIRECTORY", directory_which::B_USER_NONPACKAGED_TRANSLATORS_DIRECTORY, "")
.value("B_USER_NONPACKAGED_MEDIA_NODES_DIRECTORY", directory_which::B_USER_NONPACKAGED_MEDIA_NODES_DIRECTORY, "")
.value("B_USER_NONPACKAGED_BIN_DIRECTORY", directory_which::B_USER_NONPACKAGED_BIN_DIRECTORY, "")
.value("B_USER_NONPACKAGED_DATA_DIRECTORY", directory_which::B_USER_NONPACKAGED_DATA_DIRECTORY, "")
.value("B_USER_NONPACKAGED_FONTS_DIRECTORY", directory_which::B_USER_NONPACKAGED_FONTS_DIRECTORY, "")
.value("B_USER_NONPACKAGED_SOUNDS_DIRECTORY", directory_which::B_USER_NONPACKAGED_SOUNDS_DIRECTORY, "")
.value("B_USER_NONPACKAGED_DOCUMENTATION_DIRECTORY", directory_which::B_USER_NONPACKAGED_DOCUMENTATION_DIRECTORY, "")
.value("B_USER_NONPACKAGED_LIB_DIRECTORY", directory_which::B_USER_NONPACKAGED_LIB_DIRECTORY, "")
.value("B_USER_NONPACKAGED_HEADERS_DIRECTORY", directory_which::B_USER_NONPACKAGED_HEADERS_DIRECTORY, "")
.value("B_USER_NONPACKAGED_DEVELOP_DIRECTORY", directory_which::B_USER_NONPACKAGED_DEVELOP_DIRECTORY, "")
.value("B_USER_DEVELOP_DIRECTORY", directory_which::B_USER_DEVELOP_DIRECTORY, "")
.value("B_USER_DOCUMENTATION_DIRECTORY", directory_which::B_USER_DOCUMENTATION_DIRECTORY, "")
.value("B_USER_SERVERS_DIRECTORY", directory_which::B_USER_SERVERS_DIRECTORY, "")
.value("B_USER_APPS_DIRECTORY", directory_which::B_USER_APPS_DIRECTORY, "")
.value("B_USER_BIN_DIRECTORY", directory_which::B_USER_BIN_DIRECTORY, "")
.value("B_USER_PREFERENCES_DIRECTORY", directory_which::B_USER_PREFERENCES_DIRECTORY, "")
.value("B_USER_ETC_DIRECTORY", directory_which::B_USER_ETC_DIRECTORY, "")
.value("B_USER_LOG_DIRECTORY", directory_which::B_USER_LOG_DIRECTORY, "")
.value("B_USER_SPOOL_DIRECTORY", directory_which::B_USER_SPOOL_DIRECTORY, "")
.value("B_USER_VAR_DIRECTORY", directory_which::B_USER_VAR_DIRECTORY, "")
.value("B_APPS_DIRECTORY", directory_which::B_APPS_DIRECTORY, "")
.value("B_PREFERENCES_DIRECTORY", directory_which::B_PREFERENCES_DIRECTORY, "")
.value("B_UTILITIES_DIRECTORY", directory_which::B_UTILITIES_DIRECTORY, "")
.value("B_PACKAGE_LINKS_DIRECTORY", directory_which::B_PACKAGE_LINKS_DIRECTORY, "")
.value("B_BEOS_DIRECTORY", directory_which::B_BEOS_DIRECTORY, "")
.value("B_BEOS_SYSTEM_DIRECTORY", directory_which::B_BEOS_SYSTEM_DIRECTORY, "")
.value("B_BEOS_ADDONS_DIRECTORY", directory_which::B_BEOS_ADDONS_DIRECTORY, "")
.value("B_BEOS_BOOT_DIRECTORY", directory_which::B_BEOS_BOOT_DIRECTORY, "")
.value("B_BEOS_FONTS_DIRECTORY", directory_which::B_BEOS_FONTS_DIRECTORY, "")
.value("B_BEOS_LIB_DIRECTORY", directory_which::B_BEOS_LIB_DIRECTORY, "")
.value("B_BEOS_SERVERS_DIRECTORY", directory_which::B_BEOS_SERVERS_DIRECTORY, "")
.value("B_BEOS_APPS_DIRECTORY", directory_which::B_BEOS_APPS_DIRECTORY, "")
.value("B_BEOS_BIN_DIRECTORY", directory_which::B_BEOS_BIN_DIRECTORY, "")
.value("B_BEOS_ETC_DIRECTORY", directory_which::B_BEOS_ETC_DIRECTORY, "")
.value("B_BEOS_DOCUMENTATION_DIRECTORY", directory_which::B_BEOS_DOCUMENTATION_DIRECTORY, "")
.value("B_BEOS_PREFERENCES_DIRECTORY", directory_which::B_BEOS_PREFERENCES_DIRECTORY, "")
.value("B_BEOS_TRANSLATORS_DIRECTORY", directory_which::B_BEOS_TRANSLATORS_DIRECTORY, "")
.value("B_BEOS_MEDIA_NODES_DIRECTORY", directory_which::B_BEOS_MEDIA_NODES_DIRECTORY, "")
.value("B_BEOS_SOUNDS_DIRECTORY", directory_which::B_BEOS_SOUNDS_DIRECTORY, "")
.export_values();

/* These are hardcoded
m.attr("B_FIND_PATH_CREATE_DIRECTORY") = py::cast(B_FIND_PATH_CREATE_DIRECTORY);
m.attr("B_FIND_PATH_CREATE_PARENT_DIRECTORY") = py::cast(B_FIND_PATH_CREATE_PARENT_DIRECTORY);
m.attr("B_FIND_PATH_EXISTING_ONLY") = py::cast(B_FIND_PATH_EXISTING_ONLY);
m.attr("B_FIND_PATHS_SYSTEM_ONLY") = py::cast(B_FIND_PATHS_SYSTEM_ONLY);
m.attr("B_FIND_PATHS_USER_ONLY") = py::cast(B_FIND_PATHS_USER_ONLY);
*/
m.attr("B_FIND_PATH_CREATE_DIRECTORY") = 0x0001;
m.attr("B_FIND_PATH_CREATE_PARENT_DIRECTORY") = 0x0002;
m.attr("B_FIND_PATH_EXISTING_ONLY") = 0x0004;
m.attr("B_FIND_PATHS_SYSTEM_ONLY") = 0x0010;
m.attr("B_FIND_PATHS_USER_ONLY") = 0x0020;


py::enum_<path_base_directory>(m, "path_base_directory", "")
.value("B_FIND_PATH_INSTALLATION_LOCATION_DIRECTORY", path_base_directory::B_FIND_PATH_INSTALLATION_LOCATION_DIRECTORY, "")
.value("B_FIND_PATH_ADD_ONS_DIRECTORY", path_base_directory::B_FIND_PATH_ADD_ONS_DIRECTORY, "")
.value("B_FIND_PATH_APPS_DIRECTORY", path_base_directory::B_FIND_PATH_APPS_DIRECTORY, "")
.value("B_FIND_PATH_BIN_DIRECTORY", path_base_directory::B_FIND_PATH_BIN_DIRECTORY, "")
.value("B_FIND_PATH_BOOT_DIRECTORY", path_base_directory::B_FIND_PATH_BOOT_DIRECTORY, "")
.value("B_FIND_PATH_CACHE_DIRECTORY", path_base_directory::B_FIND_PATH_CACHE_DIRECTORY, "")
.value("B_FIND_PATH_DATA_DIRECTORY", path_base_directory::B_FIND_PATH_DATA_DIRECTORY, "")
.value("B_FIND_PATH_DEVELOP_DIRECTORY", path_base_directory::B_FIND_PATH_DEVELOP_DIRECTORY, "")
.value("B_FIND_PATH_DEVELOP_LIB_DIRECTORY", path_base_directory::B_FIND_PATH_DEVELOP_LIB_DIRECTORY, "")
.value("B_FIND_PATH_DOCUMENTATION_DIRECTORY", path_base_directory::B_FIND_PATH_DOCUMENTATION_DIRECTORY, "")
.value("B_FIND_PATH_ETC_DIRECTORY", path_base_directory::B_FIND_PATH_ETC_DIRECTORY, "")
.value("B_FIND_PATH_FONTS_DIRECTORY", path_base_directory::B_FIND_PATH_FONTS_DIRECTORY, "")
.value("B_FIND_PATH_HEADERS_DIRECTORY", path_base_directory::B_FIND_PATH_HEADERS_DIRECTORY, "")
.value("B_FIND_PATH_LIB_DIRECTORY", path_base_directory::B_FIND_PATH_LIB_DIRECTORY, "")
.value("B_FIND_PATH_LOG_DIRECTORY", path_base_directory::B_FIND_PATH_LOG_DIRECTORY, "")
.value("B_FIND_PATH_MEDIA_NODES_DIRECTORY", path_base_directory::B_FIND_PATH_MEDIA_NODES_DIRECTORY, "")
.value("B_FIND_PATH_PACKAGES_DIRECTORY", path_base_directory::B_FIND_PATH_PACKAGES_DIRECTORY, "")
.value("B_FIND_PATH_PREFERENCES_DIRECTORY", path_base_directory::B_FIND_PATH_PREFERENCES_DIRECTORY, "")
.value("B_FIND_PATH_SERVERS_DIRECTORY", path_base_directory::B_FIND_PATH_SERVERS_DIRECTORY, "")
.value("B_FIND_PATH_SETTINGS_DIRECTORY", path_base_directory::B_FIND_PATH_SETTINGS_DIRECTORY, "")
.value("B_FIND_PATH_SOUNDS_DIRECTORY", path_base_directory::B_FIND_PATH_SOUNDS_DIRECTORY, "")
.value("B_FIND_PATH_SPOOL_DIRECTORY", path_base_directory::B_FIND_PATH_SPOOL_DIRECTORY, "")
.value("B_FIND_PATH_TRANSLATORS_DIRECTORY", path_base_directory::B_FIND_PATH_TRANSLATORS_DIRECTORY, "")
.value("B_FIND_PATH_VAR_DIRECTORY", path_base_directory::B_FIND_PATH_VAR_DIRECTORY, "")
.value("B_FIND_PATH_IMAGE_PATH", path_base_directory::B_FIND_PATH_IMAGE_PATH, "")
.value("B_FIND_PATH_PACKAGE_PATH", path_base_directory::B_FIND_PATH_PACKAGE_PATH, "")
.export_values();
/*
py::enum_<path_base_directory>(m, "path_base_directory", "")
.value("B_FIND_PATH_INSTALLATION_LOCATION_DIRECTORY", 0, "")
.value("B_FIND_PATH_ADD_ONS_DIRECTORY", 1, "")
.value("B_FIND_PATH_APPS_DIRECTORY", 2, "")
.value("B_FIND_PATH_BIN_DIRECTORY", 3, "")
.value("B_FIND_PATH_BOOT_DIRECTORY", 4, "")
.value("B_FIND_PATH_CACHE_DIRECTORY", 5, "")
.value("B_FIND_PATH_DATA_DIRECTORY", 6, "")
.value("B_FIND_PATH_DEVELOP_DIRECTORY", 7, "")
.value("B_FIND_PATH_DEVELOP_LIB_DIRECTORY", 8, "")
.value("B_FIND_PATH_DOCUMENTATION_DIRECTORY", 9, "")
.value("B_FIND_PATH_ETC_DIRECTORY", 10, "")
.value("B_FIND_PATH_FONTS_DIRECTORY", 11, "")
.value("B_FIND_PATH_HEADERS_DIRECTORY", 12, "")
.value("B_FIND_PATH_LIB_DIRECTORY", 13, "")
.value("B_FIND_PATH_LOG_DIRECTORY", 14, "")
.value("B_FIND_PATH_MEDIA_NODES_DIRECTORY", 15, "")
.value("B_FIND_PATH_PACKAGES_DIRECTORY", 16, "")
.value("B_FIND_PATH_PREFERENCES_DIRECTORY", 17, "")
.value("B_FIND_PATH_SERVERS_DIRECTORY", 18, "")
.value("B_FIND_PATH_SETTINGS_DIRECTORY", 19, "")
.value("B_FIND_PATH_SOUNDS_DIRECTORY", 20, "")
.value("B_FIND_PATH_SPOOL_DIRECTORY", 21, "")
.value("B_FIND_PATH_TRANSLATORS_DIRECTORY", 22, "")
.value("B_FIND_PATH_VAR_DIRECTORY", 23, "")
.value("B_FIND_PATH_IMAGE_PATH", 1000, "")
.value("B_FIND_PATH_PACKAGE_PATH", 1001, "")
.export_values();*/

//m.attr("BVolume") = py::cast(BVolume);

m.def("find_directory", py::overload_cast<directory_which, dev_t, bool, char *, int32>(&find_directory), "", py::arg("which"), py::arg("volume"), py::arg("createIt"), py::arg("pathString"), py::arg("length"));

m.def("find_path", &find_path, "", py::arg("codePointer"), py::arg("baseDirectory"), py::arg("subPath"), py::arg("pathBuffer"), py::arg("bufferSize"));

m.def("find_path_etc", &find_path_etc, "", py::arg("codePointer"), py::arg("dependency"), py::arg("architecture"), py::arg("baseDirectory"), py::arg("subPath"), py::arg("flags"), py::arg("pathBuffer"), py::arg("bufferSize"));

m.def("find_path_for_path", &find_path_for_path, "", py::arg("path"), py::arg("baseDirectory"), py::arg("subPath"), py::arg("pathBuffer"), py::arg("bufferSize"));

m.def("find_path_for_path_etc", &find_path_for_path_etc, "", py::arg("path"), py::arg("dependency"), py::arg("architecture"), py::arg("baseDirectory"), py::arg("subPath"), py::arg("flags"), py::arg("pathBuffer"), py::arg("bufferSize"));

//m.def("find_paths", &find_paths, "", py::arg("baseDirectory"), py::arg("subPath"), py::arg("_paths"), py::arg("_pathCount"));

//m.def("find_paths_etc", &find_paths_etc, "", py::arg("architecture"), py::arg("baseDirectory"), py::arg("subPath"), py::arg("flags"), py::arg("_paths"), py::arg("_pathCount"));

m.def("find_directory", py::overload_cast<directory_which, BPath *, bool, BVolume *>(&find_directory), "", py::arg("which"), py::arg("path"), py::arg("createIt")=false, py::arg("volume")=NULL);

}
